CREATE TABLE log_entry (id INTEGER NOT NULL AUTO_INCREMENT, date DATETIME NOT NULL, url VARCHAR(256) NOT NULL, user_agent VARCHAR(256), PRIMARY KEY (id))
;
CREATE TABLE search_term (id INTEGER NOT NULL AUTO_INCREMENT, term VARCHAR(512) NOT NULL, total INTEGER NOT NULL, PRIMARY KEY (id), UNIQUE(term));
